# ****************************************************************************
# NOTES:
#
# This is an example of a production deployment that uses GitHub Pages along
# with a second "production" GitHub organisation. If you prefer to implement
# your own workflow, or do not need production deployments, then you should
# delete this file.
#
# In order for this to work, you must replace PRODUCTION_ORGANISATION below
# with the name of your production GitHub organisation, under REPOSITORY_NAME.
# You must also replace PRODUCTION_REPOSITORY below with the name of your
# production data repository.
#
# For example, if your production organisation is "my-stats-org", and your
# production data repository is "sdg-data", then use:
#
# REPOSITORY_NAME: my-stats-org/sdg-data
#
# ****************************************************************************

name: Deploy to production

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: Build data
      run: |
        python scripts/build_data.py
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        repository-name: sustainabledevelopment-kyrgyzstan/sdg-data
        token: ${{ secrets.token }}
        branch: gh-pages
        folder: _site
        clean: true
    - name: Waiting 4 minutes for production data deployment
      run: |
        sleep 240
    - name: Rebuild production
      run: |
        curl -X POST https://api.github.com/repos/sdg-kyrgyzstan/open-sdg-site-starter/dispatches \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Authorization: token ${{secrets.token}}" \
        --data '{"event_type": "rebuild-production"}'
